---
- name: Install Packages
  apt:
    name:
      #- ntp
      - python3
      #- tcpdump
      #- wget
      - openssl
      - curl
      - python3-docker
    state: latest
    update_cache: yes
    force_apt_get: yes
