---
- name: Install Packages
  apt:
    name:
      #- ntp
      #- tcpdump
      - wget
      - openssl
      - curl
      - nfs-common
      - python3
      - python3-docker    # docker modules
      - python3-jsondiff  # docker_stack module
      - python3-yaml      # docker_stack module
    state: latest
    update_cache: yes
    force_apt_get: yes
