---
- name: assign labels
  docker_node:
    hostname: "{{ inventory_hostname }}"
    labels:
      mongo.replica: "{{ hostvars[inventory_hostname]['mongo_replica_label'] }}"
  delegate_to: "{{ groups['swarm_managers'][0] }}"
