---
- name: Mount NFS volumes
  hosts: docker_nodes
  become: yes
  roles:
    - mount-nfs-volumes

- name: Copy scripts to shared NFS volume
  hosts: docker_nodes
  become: yes
  roles:
    - transfer-init-scripts

- name: Deploy stack
  hosts: swarm_managers
  become: yes
  roles:
    - deploy-stack
