---
- name: Prepare nodes
  hosts: docker_nodes
  become: yes
  roles:
    - pull-mongo-image
    - transfer-init-scripts

- name: Deploy stack
  hosts: swarm_managers
  become: yes
  roles:
    - deploy-stack
