---
- name: Create  directory /docker/mongo_sharded
  ansible.builtin.file:
    path: /docker/mongo_sharded
    state: directory
    mode: '0750'

- name: Mount NFS nfs-server:/docker-exports/mongo_sharded -> /docker/mongo_sharded
  mount:
    src: 10.211.0.1:/docker-exports/mongo_sharded
    path: /docker/mongo_sharded
    opts: "nfsvers=4,nolock,soft"
    state: mounted
    fstype: nfs

- name: Copy init scripts to remote NFS mount point
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/init-scripts/scripts"
    dest: /docker/mongo_sharded
    owner: root
    group: root
    mode: '0640'
  run_once: true
